language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

script:
  - mkdir build
  - cmake ../
  - make install
  - ./tests/basis_test
  - ./tests/tree_test
