language: cpp

dist: bionic

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libc++-dev
      env: COMPILER=clang++

install:
  - sudo apt update -qq
  - sudo apt install -qq libeigen3-dev
  - sudo apt install -qq libgsl-dev
  - sudo apt install -qq libgslcblas0
  - sudo apt install -qq libboost-all-dev
  - sudo apt install -qq doctest-dev
  
before_script:
  - export CXX=$COMPILER
  - cmake --version

script:
  - mkdir ../build
  - cd ../build
  - cmake ../Multiped/ -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release
  - cmake --build . -v
