language: cpp
compiler: gcc
dist: bionic

install:
  - sudo apt-get install libeigen3-dev

script:
  - mkdir build
  - cd build
  - cmake ../
  - make install
  - ./tests/basis_test
  - ./tests/tree_test
