dist: trusty
sudo: require

language: c++
compiler: gcc

os: linux
    addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"

install:
    -cmake
    -make install
