version: 2.1

orbs:
  codecov: codecov/codecov@1.1.3

jobs:
    test:
        machine:
            image: ubuntu-2004:202010-01
            
        steps:
            - run: sudo apt-get update
            - run: sudo apt-get install libgsl-dev
            - run: sudo apt-get install libboost-all-dev
            - run: sudo apt-get install doctest-dev
            - run: sudo apt-get install lcov
            - run: cd .. && git clone https://cpp977:A*u1t5o!s@github.com/cpp977/Multiped
            - run: cd .. && mkdir build
            - run: cd ../build && cmake ../Multiped -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
            - run: cd ../build && cmake --build .
            - run: 
                command: cd ../build/tests && ctest
                no_output_timeout: 2h
            - run: cd ../build/tests && lcov --capture --directory . --output-file coverage.info
            - run: cd ../build/tests && lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
            - run: cd ../build/tests && lcov --remove coverage.info '/home/circleci/build/thirdparty/*' --output-file coverage.info # filter system-files
            - run: cd ../build/tests && lcov --list coverage.info # debug info
            - run: cd ../build/tests && cat coverage.info
            - codecov/upload:
                file: ../build/tests/coverage.info
                token: 6604ed1a-6dd1-4021-8450-93cb22163632
            
workflows:
    build_and_test:
        jobs:
            - test
            
