version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-2004:202010-01
            
        steps:
            - checkout
            - run: sudo apt-get update
            - run: sudo apt-get install libgsl-dev
            - run: sudo apt-get install libboost-all-dev
            - run: sudo apt-get install doctest-dev
            - run: mkdir ../build
            - run: cd ../build && cmake ../project
            - run: cd ../build && cmake --build .
    test:
        machine:
            image: ubuntu-2004:202010-01
            
        steps:
            - checkout
            - run: sudo apt-get update
            - run: sudo apt-get install libgsl-dev
            - run: sudo apt-get install libboost-all-dev
            - run: sudo apt-get install doctest-dev
            - run: mkdir ../build
            - run: cd ../build && cmake ../project
            - run: cd ../build && cmake --build .
            - run: cd ../build/tests && ./basis_test
            - run: cd ../build/tests && ./tree_test
            
workflows:
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
            
