version: 2.1
jobs:
    test:
        machine:
            image: ubuntu-2004:202010-01
            
        steps:
            - checkout
            - run: sudo apt-get update
            - run: sudo apt-get install libgsl-dev
            - run: sudo apt-get install libboost-all-dev
            - run: sudo apt-get install doctest-dev
            - run: sudo apt-get install lcov
            - run: mkdir ../build
            - run: cd ../build && cmake ../project -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
            - run: cd ../build && cmake --build .
            - run: 
                command: cd ../build/tests && ctest
                no_output_timeout: 2h
            - run: cd ../build/tests && lcov --capture --directory . --output-file coverage.info
            - run: cd ../build/tests && lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
            - run: cd ../build/tests && lcov --list coverage.info # debug info
            - run: cd ../build/tests && bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
            
workflows:
    build_and_test:
        jobs:
            - test
            
