version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-2004:202010-01

          
        steps:
            - checkout
            - run: g++ --version
            - run: ls -la
            - run: mkdir build && cd build
            - run: ls -la
            - run: cmake ../Tensor
            
workflows:
    build_and_test:
        jobs:
            - build
