version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-2004:202010-01
            
        steps:
            - checkout
            - run: g++ --version
            - run: sudo apt-get update
            - run: sudo apt-get install libgsl-dev
            - run: sudo apt-get install libboost-all-dev
            - run: mkdir ../build
            - run: cd ../build && cmake ../project
            
workflows:
    build_and_test:
        jobs:
            - build
