function(enable_doxygen)
  if(XPED_ENABLE_DOXYGEN)
    set(DOXYGEN_HAVE_DOT YES)
    set(DOXYGEN_CALLER_GRAPH YES)
    set(DOXYGEN_CALL_GRAPH YES)
    set(DOXYGEN_EXTRACT_ALL YES)
    set(DOXYGEN_EXAMPLE_PATH "docs/snippets;src;include/Xped")
    set(DOXYGEN_EXTENSION_MAPPING "hpp=C++")
    set(DOXYGEN_EXCLUDE "vcpkg;doxygen-awesome-css;triplets;cmake;docs/snippets;tests;README.md;tools")
    set(DOXYGEN_EXCLUDE_SYMBOLS "std;stan;yas")
    set(DOXYGEN_HTML_EXTRA_FILES "doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js")
    set(DOXYGEN_HTML_EXTRA_STYLESHEET "doxygen-awesome-css/doxygen-awesome.css;doxygen-awesome-css/doxygen-awesome-sidebar-only.css;doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css")
    set(DOXYGEN_HTML_COLORSTYLE LIGHT)
    set(DOXYGEN_GENERATE_TREEVIEW YES)
    set(DOXYGEN_USE_MATHJAX YES)
    set(DOXYGEN_HTML_HEADER "docs/extras/header.html")
    set(DOXYGEN_HTML_FOOTER "docs/extras/footer.html")
    find_package(Doxygen REQUIRED dot)
    doxygen_add_docs(docs ${PROJECT_SOURCE_DIR})

  endif()
endfunction()
